### ISSUE TITLE
Any way to get a newer version with the latest openzwave ?

### ISSUE THREAD

**Issue by MoBOatGVA** [ruimarinho/docker-openzwave#2]
Hi,

is there any way you can create a never version of your docker ?

**Comment by ruimarinho** [comment]
Done. Updated to `1.6.963`. Please wait for an hour or so before the image gets updated on Docker Hub. 

Note that OpenZWave control panel is now unmaintained.

**Comment by MoBOatGVA** [comment]
First: THANKS YOU
Then: Hmmm... looks like something went wrong : OpenZwave Version 1.4.2816 Starting Up :o(

Thanks

**Comment by ruimarinho** [comment]
Looks good here:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/288709/69497769-719c1280-0ed8-11ea-9a02-fb36ea48f903.png">

**Comment by MoBOatGVA** [comment]
Indeed... but took not 1 hour but 1 day on my side ;o)
THANKS FOR THIS, working perfectly
